replicaCount: 1

image:
  repository: registry.gitlab.com/group/uno-arena/spectator-view
  digest: ""

env:
  SERVICE_NAME: spectator-view
  API_URL: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
