replicaCount: 1

env:
  REDIS_URL: redis://redis.uno-arena.svc.cluster.local:6379/5
  KAFKA_BROKERS: kafka.uno-arena.svc.cluster.local:9092

projectionRebuilder:
  enabled: false

existingSecret: spectator-view-secrets
