apiVersion: v1
kind: ServiceAccount
metadata:
  name: spectator-view
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spectator-view-projection-rebuilder
automountServiceAccountToken: false
