apiVersion: v1
kind: ServiceAccount
metadata:
  name: spectator-view
automountServiceAccountToken: false
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spectator-view-projection-rebuilder
automountServiceAccountToken: false
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
