#!/usr/bin/env bash
# Deterministically render the exact, repository-owned local foundation desired state.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${LOCAL_DIR}/../.." && pwd)"
OUTPUT="${1:?usage: render-foundation.sh OUTPUT}"

command -v helm >/dev/null 2>&1 || { echo "helm is required" >&2; exit 1; }
"${LOCAL_DIR}/vendor/verify.sh" >/dev/null

tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

# kind node certificates omit routable node-IP SANs. Keep the exception in this
# local-only generated artifact; the production foundation never consumes it.
ruby -e '
  input, output = ARGV
  body = File.read(input)
  needle = "        - --kubelet-use-node-status-port\n"
  abort "metrics-server argument anchor missing" unless body.scan(needle).length == 1
  body = body.sub(needle, needle + "        - --kubelet-insecure-tls\n")
  liveness = <<~YAML.lines.map { |line| "        #{line}" }.join
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /livez
        port: https
        scheme: HTTPS
      periodSeconds: 10
  YAML
  hardened_liveness = liveness
    .sub("failureThreshold: 3", "failureThreshold: 12")
    .sub("periodSeconds: 10", "periodSeconds: 10\n          timeoutSeconds: 10")
  startup = <<~YAML.lines.map { |line| "        #{line}" }.join
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /livez
        port: https
        scheme: HTTPS
      periodSeconds: 10
      timeoutSeconds: 10
  YAML
  abort "metrics-server liveness anchor missing" unless body.scan(liveness).length == 1
  body = body.sub(liveness, hardened_liveness + startup)
  readiness = <<~YAML.lines.map { |line| "        #{line}" }.join
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: https
        scheme: HTTPS
      initialDelaySeconds: 20
      periodSeconds: 10
  YAML
  hardened_readiness = readiness.sub("periodSeconds: 10", "periodSeconds: 10\n          timeoutSeconds: 10")
  abort "metrics-server readiness anchor missing" unless body.scan(readiness).length == 1
  File.write(output, body.sub(readiness, hardened_readiness))
' "${LOCAL_DIR}/vendor/metrics-server/components.yaml" "${tmp_dir}/metrics-server.yaml"

# 00-namespaces.yaml owns the namespace inventory. The upstream cert-manager
# bundle repeats its namespace, which Argo rejects as a repeated resource.
ruby -e '
  input, output = ARGV
  body = File.read(input)
  namespace = "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: cert-manager\n\n---\n"
  abort "cert-manager namespace anchor changed" unless body.scan(namespace).length == 1
  File.write(output, body.sub(namespace, ""))
' "${LOCAL_DIR}/vendor/cert-manager/cert-manager.yaml" "${tmp_dir}/cert-manager.yaml"

{
  printf '%s\n' '# Generated by infrastructure/local-production/gitops/render-foundation.sh; do not edit.'
  for file in \
    "${LOCAL_DIR}/manifests/00-namespaces.yaml" \
    "${LOCAL_DIR}/vendor/gateway-api/standard-install.yaml" \
    "${tmp_dir}/cert-manager.yaml"; do
    printf '%s\n' '---'
    sed '/^# Generated by /d' "${file}"
  done

  printf '%s\n' '---'
  helm template external-secrets "${LOCAL_DIR}/vendor/external-secrets/external-secrets-2.7.0.tgz" \
    --namespace external-secrets --set installCRDs=true

  printf '%s\n' '---'
  cat "${tmp_dir}/metrics-server.yaml"

  printf '%s\n' '---'
  helm template istio-base "${REPO_ROOT}/infrastructure/istio/charts/base" \
    --namespace istio-system
  printf '%s\n' '---'
  helm template istiod "${REPO_ROOT}/infrastructure/istio/charts/istiod" \
    --namespace istio-system \
    --values "${REPO_ROOT}/infrastructure/istio/values/istiod.kind.yaml" \
    --set gatewayClasses.istio.service.spec.type=NodePort
  printf '%s\n' '---'
  helm template istio-cni "${REPO_ROOT}/infrastructure/istio/charts/cni" \
    --namespace istio-system \
    --values "${REPO_ROOT}/infrastructure/istio/values/cni.kind.yaml"
  printf '%s\n' '---'
  helm template ztunnel "${REPO_ROOT}/infrastructure/istio/charts/ztunnel" \
    --namespace istio-system \
    --values "${REPO_ROOT}/infrastructure/istio/values/ztunnel.kind.yaml"

  for file in \
    "${LOCAL_DIR}/manifests/10-external-secrets-local.yaml" \
    "${LOCAL_DIR}/manifests/20-ca-bootstrap.yaml" \
    "${LOCAL_DIR}/manifests/21-local-certificates.yaml" \
    "${LOCAL_DIR}/manifests/30-gateway.yaml" \
    "${LOCAL_DIR}/manifests/40-ambient-security.yaml"; do
    printf '%s\n' '---'
    sed '/^# Generated by /d' "${file}"
  done
} >"${OUTPUT}"
