apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-projection-rebuilder
automountServiceAccountToken: false
