apiVersion: v1
kind: ServiceAccount
metadata:
  name: ranking
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ranking-leaderboard-snapshotter
automountServiceAccountToken: false
