apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
automountServiceAccountToken: false
{{- if .Values.provisioningWorker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-provisioning-worker
automountServiceAccountToken: false
{{- end }}
{{- if .Values.seedingWorker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-seeding-worker
automountServiceAccountToken: false
{{- end }}
{{- if .Values.completionWorker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-completion-worker
automountServiceAccountToken: false
{{- end }}
