apiVersion: v1
kind: ServiceAccount
metadata: {name: debezium-connect, namespace: uno-arena}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: debezium-connect-registrar, namespace: uno-arena}
automountServiceAccountToken: false
---
{{ tpl (.Files.Get "files/connect.yaml") . }}
---
{{ tpl (.Files.Get "files/register.yaml") . }}
