{{- range $context, $size := .Values.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-{{ $context }}-data
  namespace: uno-arena
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/name: postgres-{{ $context }}
    app.kubernetes.io/part-of: uno-arena
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ $.Values.storageClassName }}
  resources:
    requests:
      storage: {{ $size }}
---
{{- end }}
